import { fireEvent, render, screen } from '@testing-library/react-native';
import React from 'react';
import {
  getCollections,
  getRecentlyAddedRoms,
  getRecommendations,
  getStats,
  getVirtualCollections,
} from '../../api/rommClient';
import {
  RommCollection,
  RommRecommendation,
  RommRom,
  RommStats,
  RommVirtualCollection,
} from '../../api/types';
import { useAuth } from '../../auth/AuthContext';
import { createAuthValue } from '../../testUtils/mockAuth';
import { createScreenProps } from '../../testUtils/navigation';
import { HomeTab } from '../HomeTab';

jest.mock('../../auth/AuthContext');
jest.mock('../../api/rommClient');

const mockedUseAuth = jest.mocked(useAuth);
const mockedGetStats = jest.mocked(getStats);
const mockedGetRecentlyAddedRoms = jest.mocked(getRecentlyAddedRoms);
const mockedGetRecommendations = jest.mocked(getRecommendations);
const mockedGetCollections = jest.mocked(getCollections);
const mockedGetVirtualCollections = jest.mocked(getVirtualCollections);

const STATS: RommStats = {
  PLATFORMS: 33,
  ROMS: 3164,
  SAVES: 2,
  STATES: 1,
  SCREENSHOTS: 1,
  TOTAL_FILESIZE_BYTES: 679034329497,
};

const RECENT: RommRom[] = [
  { id: 1, name: 'Wild West Shootout', platform_id: 1, platform_slug: 'wii' },
];

const RECOMMENDATIONS: RommRecommendation[] = [
  {
    rom: { id: 2, name: 'Beyond Good and Evil', platform_id: 2 },
    score: 0.8,
    reasons: [{ facet: 'franchise', value: '' }],
    seed_rom_id: 9,
    seed_rom_name: 'Fur Fighters',
  },
];

const COLLECTIONS: RommCollection[] = [
  { id: 3, name: 'Platformers', rom_count: 12 },
];

const VIRTUAL_COLLECTIONS: RommVirtualCollection[] = [
  { id: 'collection-1', name: 'The Legend of Zelda', rom_count: 5 },
];

function renderTab() {
  const { navigation, props } = createScreenProps('Main', undefined);
  return {
    navigation,
    rendered: render(<HomeTab navigation={props.navigation} />),
  };
}

beforeEach(() => {
  mockedUseAuth.mockReturnValue(createAuthValue());
  mockedGetStats.mockResolvedValue(STATS);
  mockedGetRecentlyAddedRoms.mockResolvedValue([...RECENT]);
  mockedGetRecommendations.mockResolvedValue([...RECOMMENDATIONS]);
  mockedGetCollections.mockResolvedValue([...COLLECTIONS]);
  mockedGetVirtualCollections.mockResolvedValue([...VIRTUAL_COLLECTIONS]);
});

describe('HomeTab', () => {
  it('shows a spinner while loading', async () => {
    mockedGetStats.mockReturnValueOnce(new Promise(() => {}));
    await renderTab().rendered;

    expect(screen.getByTestId('home-loading')).toBeOnTheScreen();
  });

  it('shows library stats', async () => {
    await renderTab().rendered;

    expect(await screen.findByText('3,164')).toBeOnTheScreen();
    expect(screen.getByText('Games')).toBeOnTheScreen();
    expect(screen.getByText('33')).toBeOnTheScreen();
    expect(screen.getByText('632.4 GB')).toBeOnTheScreen();
  });

  it('shows the recently added shelf and opens the details screen for a rom', async () => {
    const { navigation, rendered } = renderTab();
    await rendered;

    expect(await screen.findByTestId('home-recent-tile-1')).toHaveTextContent(
      /Wild West Shootout/,
    );

    await fireEvent.press(screen.getByTestId('home-recent-tile-1'));

    expect(navigation.navigate).toHaveBeenCalledWith('GameDetails', {
      romId: 1,
      romName: 'Wild West Shootout',
      platformSlug: 'wii',
    });
  });

  it('shows the recommended shelf with a "because you played" reason', async () => {
    await renderTab().rendered;

    expect(
      await screen.findByTestId('home-recommended-tile-2'),
    ).toHaveTextContent('Beyond Good and Evil');
    expect(
      screen.getByText('Because you played Fur Fighters'),
    ).toBeOnTheScreen();
  });

  it('shows the collections shelf and opens the collection', async () => {
    const { navigation, rendered } = renderTab();
    await rendered;

    await fireEvent.press(await screen.findByTestId('home-collections-tile-3'));

    expect(navigation.navigate).toHaveBeenCalledWith('Roms', {
      collectionId: 3,
      collectionName: 'Platformers',
    });
  });

  it('shows the autogenerated collections shelf and opens the collection', async () => {
    const { navigation, rendered } = renderTab();
    await rendered;

    await fireEvent.press(
      await screen.findByTestId('home-virtual-collections-tile-collection-1'),
    );

    expect(navigation.navigate).toHaveBeenCalledWith('Roms', {
      virtualCollectionId: 'collection-1',
      virtualCollectionName: 'The Legend of Zelda',
    });
  });

  it('hides a shelf whose data failed to load without failing the page', async () => {
    mockedGetRecommendations.mockRejectedValueOnce(new Error('unavailable'));
    await renderTab().rendered;

    expect(await screen.findByTestId('home-recent-tile-1')).toBeOnTheScreen();
    expect(screen.queryByTestId('home-recommended')).toBeNull();
    expect(screen.queryByText('unavailable')).toBeNull();
  });

  it('shows the error and retries when everything fails', async () => {
    mockedGetStats.mockRejectedValueOnce(new Error('Failed to fetch'));
    mockedGetRecentlyAddedRoms.mockRejectedValueOnce(
      new Error('Failed to fetch'),
    );
    mockedGetRecommendations.mockRejectedValueOnce(
      new Error('Failed to fetch'),
    );
    mockedGetCollections.mockRejectedValueOnce(new Error('Failed to fetch'));
    mockedGetVirtualCollections.mockRejectedValueOnce(
      new Error('Failed to fetch'),
    );
    await renderTab().rendered;

    expect(await screen.findByText('Failed to fetch')).toBeOnTheScreen();

    await fireEvent.press(screen.getByTestId('retry-button'));

    expect(await screen.findByText('3,164')).toBeOnTheScreen();
  });
});
