import { fireEvent, render, screen } from '@testing-library/react-native';
import React from 'react';
import { VirtualCollectionShelf } from '../VirtualCollectionShelf';

const COLLECTIONS = [
  { id: 'collection-1', name: 'The Legend of Zelda', rom_count: 12 },
  {
    id: 'collection-2',
    name: 'Metroid',
    rom_count: 1,
    path_covers_large: ['/assets/romm/resources/9/cover.png'],
  },
];

describe('VirtualCollectionShelf', () => {
  it('renders a title and a tile per collection, with a pluralised count', async () => {
    await render(
      <VirtualCollectionShelf
        title="Autogenerated collections"
        collections={COLLECTIONS}
        serverUrl="https://romm.test"
        onSelect={jest.fn()}
        testID="virtual-collections-shelf"
      />,
    );

    expect(screen.getByText('Autogenerated collections')).toBeOnTheScreen();
    expect(screen.getByText('The Legend of Zelda')).toBeOnTheScreen();
    expect(screen.getByText('12 games')).toBeOnTheScreen();
    expect(screen.getByText('1 game')).toBeOnTheScreen();
  });

  it('falls back to the first grouped cover when there is no own cover', async () => {
    await render(
      <VirtualCollectionShelf
        title="Autogenerated collections"
        collections={COLLECTIONS}
        serverUrl="https://romm.test"
        onSelect={jest.fn()}
        testID="virtual-collections-shelf"
      />,
    );

    expect(
      screen.getByTestId('virtual-collections-shelf-tile-collection-2'),
    ).toBeOnTheScreen();
  });

  it('renders nothing when there are no collections', async () => {
    await render(
      <VirtualCollectionShelf
        title="Autogenerated collections"
        collections={[]}
        serverUrl="https://romm.test"
        onSelect={jest.fn()}
        testID="virtual-collections-shelf"
      />,
    );

    expect(screen.queryByTestId('virtual-collections-shelf')).toBeNull();
  });

  it('reports the collection whose tile was pressed', async () => {
    const onSelect = jest.fn();
    await render(
      <VirtualCollectionShelf
        title="Autogenerated collections"
        collections={COLLECTIONS}
        serverUrl="https://romm.test"
        onSelect={onSelect}
        testID="virtual-collections-shelf"
      />,
    );

    await fireEvent.press(
      screen.getByTestId('virtual-collections-shelf-tile-collection-2'),
    );

    expect(onSelect).toHaveBeenCalledWith(COLLECTIONS[1]);
  });
});
