// Loosely typed to survive RomM API changes across versions.
// Only fields the app actually relies on are required; everything else is optional.

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type: string;
  expires: number;
  refresh_expires: number;
}

export interface RommPlatform {
  id: number;
  name: string;
  slug?: string;
  fs_slug?: string;
  rom_count?: number;
  [key: string]: unknown;
}

export interface RommRom {
  id: number;
  name: string;
  platform_id: number;
  platform_slug?: string;
  platform_name?: string;
  platform_display_name?: string;
  fs_name?: string;
  fs_extension?: string;
  has_file_on_disk?: boolean;
  url_cover?: string;
  [key: string]: unknown;
}

export interface RommCollection {
  id: number;
  name: string;
  description?: string;
  rom_count: number;
  url_cover?: string | null;
  [key: string]: unknown;
}

/**
 * A RomM "autogenerated" (virtual) collection: games grouped on the fly by a
 * shared metadata facet (IGDB collection/series, franchise, genre, play
 * mode, or developer) rather than a user-curated list. Its id is a derived
 * string, not a database id.
 */
export interface RommVirtualCollection {
  id: string;
  name: string;
  description?: string;
  rom_count: number;
  path_cover_small?: string | null;
  path_cover_large?: string | null;
  path_covers_small?: string[];
  path_covers_large?: string[];
  [key: string]: unknown;
}

/** RomM's source-agnostic aggregate of a rom's metadata (IGDB and others),
 * already merged and sorted server-side — see `RommRomDetail.metadatum`. */
export interface RommRomMetadata {
  genres: string[];
  franchises: string[];
  collections: string[];
  companies: string[];
  publishers: string[];
  developers: string[];
  game_modes: string[];
  age_ratings: string[];
  player_count: string;
  first_release_date: number | null;
  average_rating: number | null;
}

/** Full rom detail, as returned by GET /api/roms/{id}. */
export interface RommRomDetail extends RommRom {
  summary?: string | null;
  regions?: string[];
  languages?: string[];
  is_identified?: boolean;
  metadatum?: RommRomMetadata;
}

export interface RommRecommendationReason {
  facet: string;
  value: string;
}

export interface RommRecommendation {
  rom: RommRom;
  score: number;
  reasons: RommRecommendationReason[];
  seed_rom_id?: number | null;
  seed_rom_name?: string | null;
}

/** Shape of GET /api/stats, keys as RomM returns them. */
export interface RommStats {
  PLATFORMS: number;
  ROMS: number;
  SAVES: number;
  STATES: number;
  SCREENSHOTS: number;
  TOTAL_FILESIZE_BYTES: number;
}

export class RommApiError extends Error {
  status?: number;

  constructor(message: string, status?: number) {
    super(message);
    this.name = 'RommApiError';
    this.status = status;
  }
}
