// Loosely typed to survive RomM API changes across versions.
// Only fields the app actually relies on are required; everything else is optional.

/**
 * POST /api/auth/device/init: a device authorization flow (RFC 8628 style)
 * waiting for the user to approve it in RomM's web UI.
 */
export interface DeviceAuthInitResponse {
  /** Secret: what the device polls with. */
  device_code: string;
  /** Short code the user confirms on RomM's approval page. */
  user_code: string;
  /** Web UI path of the approval page, e.g. "/pair/device". */
  verification_path: string;
  /** The same with `?user_code=` filled in, for a QR code. */
  verification_path_complete: string;
  expires_in: number;
  /** Seconds to wait between polls. */
  interval: number;
}

/** POST /api/auth/device/token once the user has approved. */
export interface DeviceAuthTokenResponse {
  /** A client API token (`rmm_...`). */
  access_token: string;
  device_id: string;
  scopes: string[];
  expires_at: string | null;
}

/** The bits of GET /api/users/me the app reads. */
export interface RommUser {
  id: number;
  username: string;
}

export interface RommPlatform {
  id: number;
  name: string;
  slug?: string;
  fs_slug?: string;
  rom_count?: number;
  [key: string]: unknown;
}

export interface RommRom {
  id: number;
  name: string;
  platform_id: number;
  platform_slug?: string;
  platform_name?: string;
  platform_display_name?: string;
  fs_name?: string;
  fs_extension?: string;
  has_file_on_disk?: boolean;
  url_cover?: string;
  [key: string]: unknown;
}

export interface RommCollection {
  id: number;
  name: string;
  description?: string;
  rom_count: number;
  url_cover?: string | null;
  [key: string]: unknown;
}

/**
 * A RomM "autogenerated" (virtual) collection: games grouped on the fly by a
 * shared metadata facet (IGDB collection/series, franchise, genre, play
 * mode, or developer) rather than a user-curated list. Its id is a derived
 * string, not a database id.
 */
export interface RommVirtualCollection {
  id: string;
  name: string;
  description?: string;
  rom_count: number;
  path_cover_small?: string | null;
  path_cover_large?: string | null;
  path_covers_small?: string[];
  path_covers_large?: string[];
  [key: string]: unknown;
}

/** RomM's source-agnostic aggregate of a rom's metadata (IGDB and others),
 * already merged and sorted server-side — see `RommRomDetail.metadatum`. */
export interface RommRomMetadata {
  genres: string[];
  franchises: string[];
  collections: string[];
  companies: string[];
  publishers: string[];
  developers: string[];
  game_modes: string[];
  age_ratings: string[];
  player_count: string;
  first_release_date: number | null;
  average_rating: number | null;
}

/** Full rom detail, as returned by GET /api/roms/{id}. */
export interface RommRomDetail extends RommRom {
  summary?: string | null;
  regions?: string[];
  languages?: string[];
  is_identified?: boolean;
  metadatum?: RommRomMetadata;
}

export interface RommRecommendationReason {
  facet: string;
  value: string;
}

export interface RommRecommendation {
  rom: RommRom;
  score: number;
  reasons: RommRecommendationReason[];
  seed_rom_id?: number | null;
  seed_rom_name?: string | null;
}

/** Shape of GET /api/stats, keys as RomM returns them. */
export interface RommStats {
  PLATFORMS: number;
  ROMS: number;
  SAVES: number;
  STATES: number;
  SCREENSHOTS: number;
  TOTAL_FILESIZE_BYTES: number;
}

/** The 202 body of POST /api/streaming/sessions: a container is reserved and
 * the game is on its way up. The room URL follows on the session's status. */
export interface RommLaunchingSession {
  platform: string;
  container: string;
  label: string;
  rom_name: string;
  claimed_at: string;
}

export interface RommSessionTermination {
  ended_by?: string | null;
  reason?: string | null;
  ended_at?: string | null;
  platform?: string | null;
  rom_id?: number | null;
  rom_name?: string | null;
}

/** GET .../status and POST .../heartbeat for a platform's streaming session. */
export interface RommSessionStatus {
  status: 'active' | 'ended';
  platform: string;
  /** The room URL once the stream is up (RomM releases that report it). */
  host?: string | null;
  extraction_phase?: string | null;
  termination?: RommSessionTermination | null;
}

export interface RommMemoryCardSummary {
  file_count: number;
  total_bytes: number;
  game_codes: string[];
}

/** The 428 body of a claim: the container still holds a memory card nobody
 * has decided about. Claim again with `card_import` set to answer. */
export interface RommMemoryCardImportRequired {
  code: 'memory_card_import_required';
  outcome: 'found' | 'unreadable';
  summary?: RommMemoryCardSummary | null;
  reason?: string | null;
}

export class RommApiError extends Error {
  status?: number;

  constructor(message: string, status?: number) {
    super(message);
    this.name = 'RommApiError';
    this.status = status;
  }
}

export class MemoryCardImportRequiredError extends RommApiError {
  details: RommMemoryCardImportRequired;

  constructor(details: RommMemoryCardImportRequired) {
    super(
      'The streaming container holds a memory card to adopt or discard',
      428,
    );
    this.name = 'MemoryCardImportRequiredError';
    this.details = details;
  }
}
